apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: multi-disk-vm
  namespace: multi-disk-demo
spec:
  runStrategy: Always
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  template:
    spec:
      domain:
        devices:
          disks:
          - name: rootdisk
            disk: {}
            bootOrder: 1
          - name: datadisk
            disk: {}
          - name: cloudinitdisk
            disk: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: multi-disk-rootdisk
      - name: datadisk
        dataVolume:
          name: multi-disk-datadisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: redhat
            chpasswd:
              expire: false
  dataVolumeTemplates:
  - metadata:
      name: multi-disk-rootdisk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: lvms-vg1
      source:
        registry:
          pullMethod: node
          url: docker://quay.io/containerdisks/fedora:latest
  - metadata:
      name: multi-disk-datadisk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: lvms-vg1-retain
      source:
        blank: {}
