apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gpu-vm
  namespace: gpu-passthrough
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        app: gpu-workload
    spec:
      domain:
        cpu:
          cores: 4
        memory:
          guest: 8Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          gpus:
          - deviceName: nvidia.com/GA102GL_A10
            name: gpu1
      volumes:
      - name: rootdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:43
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
