= API Integration
:navtitle: API Guide

== Overview

This module covers the API for OpenShift Virtualization, including an overview of component API objects and the key fields within each object.

The API is powerful feature which can be leveraged for tighter product integrations with both OpenShift Virtualization and the underlying OpenShift Container Platform.

== What's Covered

The topics covered in this section are:

* The key API objects related to virtualization, separated by domain (Virtual Machines, Networking, Storage, etc)
* The role of each API object
* How API objects relate to one another (some are higher level abstractions of other objects)
* The essential fields in each API object (as well as each field's role and accepted values)
* Higher level API functions (snapshot, restore & cloning)
* How to observe and manage object state (VMs, snapshots and cloning)
* How to export VMs and volumes for import onto other clusters

== Before Proceeding

You'll need the following prerequisites to complete this section:

* OpenShift v4.18+ cluster with OpenShift Virtualization installed
* Cluster-level admin access (or the `kubeadmin` account credentials for test or single-tenant clusters)
* Understanding of REST APIs and related HTTP CRUD operations (GET, PUT, POST, PATCH, DELETE), token-based authentication, json, etc
* REST API developer tool (such as Postman, cURL, etc)

== Sections

xref:api_component_overview.adoc[API Component Overview]::
An overview of the API components of OpenShift Virtualization.

== Next Steps

Once you complete this module, you should (hopefully) have enough of an understanding to begin integrating your own product with OpenShift Virtualization.
We've tried to mention any gotchas or tripping points that we've encountered with other vendor integrations into this guide, to reduce the time to market for our future (and current) partners.

== See Also
* link:https://kubevirt.io/api-reference/main/index.html[KubeVirt API Reference,window=_blank]
* link:https://kubevirt.io/user-guide/architecture/[KubeVirt Architecture,window=_blank]

