apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: nfs-rwx
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
      volumeMode: Filesystem
    - accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
  cloneStrategy: copy
