name: Feature Request / New Idea
description: Suggest a new tutorial, improvement, or feature for the cookbook
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! We'd love to hear your ideas.

  - type: dropdown
    id: type
    attributes:
      label: What type of contribution is this?
      description: Select the category
      options:
        - New tutorial/guide
        - Enhancement to existing tutorial
        - New troubleshooting section
        - New example/manifest
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe your idea
      placeholder: |
        Example: Add a tutorial on how to configure SR-IOV for VMs...
        Example: Include troubleshooting steps for network connectivity issues...
        Example: Add RHEL VM examples with custom cloud-init...
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why is this valuable?
      description: Who would benefit and how?
      placeholder: |
        This would help users who need high-performance networking...
        Many users struggle with this specific scenario...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Links to documentation, examples, or related resources
    validations:
      required: false

