apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: web-vm
  namespace: netpol-demo
  labels:
    app: web
    role: frontend
spec:
  runStrategy: Always
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: web
        role: frontend
    spec:
      domain:
        devices: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:40
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: changeme
              chpasswd:
                expire: false
              packages:
                - nginx
              runcmd:
                - systemctl enable --now nginx
