apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: bridge-demo-vm
  namespace: bridge-demo
  labels:
    app: bridge-demo-vm
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: bridge-demo-volume
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 33Gi
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
  template:
    metadata:
      labels:
        app: bridge-demo-vm
    spec:
      domain:
        devices:
          disks:
          - name: datavolumedisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            model: virtio
            name: nic-linux-bridge
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: lnbr0-nad
        name: nic-linux-bridge
      volumes:
      - name: datavolumedisk
        dataVolume:
          name: bridge-demo-volume
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp2s0:
                addresses:
                - 192.168.50.10/24
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
