apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn-localnet
spec:
  namespaceSelector: 
    matchExpressions: 
    - key: kubernetes.io/metadata.name
      operator: In 
      values: ["vm-guests-localnet"]
  network:
    topology: Localnet 
    localnet:
        role: Secondary 
        physicalNetworkName: localnet1 
        ipam:
          mode: Disabled
