apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-localnet-vm
  namespace: vm-guests-localnet
  labels:
    app: fedora-localnet-vm
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: fedora-localnet-volume
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 33Gi
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
  template:
    metadata:
      labels:
        app: fedora-localnet-vm
    spec:
      domain:
        devices:
          disks:
          - name: datavolumedisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
          - name: secondary_localnet
            bridge: {}
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
      - name: default
        pod: {}
      - name: secondary_localnet
        multus:
          networkName: cudn-localnet
      volumes:
      - name: datavolumedisk
        dataVolume:
          name: fedora-localnet-volume
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
            packages:
            - python3
            runcmd:
            - echo "<h1>Welcome to OpenShift Virtualization Localnet!</h1>" > /root/index.html
            - cd /root && nohup python3 -m http.server 8080 > /dev/null 2>&1 &
