apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: lnbr0-policy
spec:
  desiredState:
    interfaces:
    - name: lnbr0
      description: static linux bridge with ens1 as a port
      type: linux-bridge
      state: up
      ipv4:
        address:
        - ip: 192.168.1.89
          prefix-length: 24
        dhcp: false
        enabled: true
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens1
