apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  clusterIP: None
  selector:
    kubevirt.io/domain: fedora-app-vm
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
