apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-with-upload
  namespace: imported-vms
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm-with-upload-disk
      spec:
        source:
          upload: {}
        storage:
          resources:
            requests:
              storage: 10Gi
  runStrategy: RerunOnFailure
  template:
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: vm-with-upload-disk
          name: rootdisk
