apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webserver-vm-2
  namespace: golden-images
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: webserver-vm-2-disk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora-nginx-golden
          namespace: golden-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: RerunOnFailure
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  template:
    spec:
      domain:
        devices: {}
      volumes:
        - dataVolume:
            name: webserver-vm-2-disk
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              hostname: webserver-vm-2
              fqdn: webserver-vm-2.example.com
          name: cloudinitdisk
