apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-odf
  namespace: default
spec:
  runStrategy: Halted
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm-odf
    spec:
      domain:
        devices: {}
      volumes:
        - name: boot-disk
          dataVolume:
            name: test-vm-odf-boot
  dataVolumeTemplates:
    - metadata:
        name: test-vm-odf-boot
      spec:
        source:
          registry:
            url: docker://quay.io/containerdisks/fedora:latest
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: ocs-storagecluster-ceph-rbd