apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-imported-vm
  namespace: imported-vms
  labels:
    app: fedora-imported
spec:
  runStrategy: RerunOnFailure
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  template:
    spec:
      domain:
        devices: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: fedora-imported-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora123
              chpasswd: { expire: false }
              ssh_pwauth: true
