apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-quickstart
  namespace: default
spec:
  runStrategy: Always
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-quickstart
    spec:
      domain:
        devices: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True